name: geekfleet
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_database: ^4.4.0
  firebase_storage: ^5.0.1
  image_picker: ^0.6.7+17
  provider: ^4.3.3
  rxdart: ^0.20.0
  cached_network_image: any
  mvc_pattern: ^3.4.1
  video_thumbnail: ^0.2.4
  firebase_messaging: any
  shared_preferences: ^0.5.12+4
  flutter_absolute_path: any
  photo_view: ^0.10.2
  in_app_purchase: any





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/bg.png
    - images/bg2.png
    - images/gfblack.png
    - images/gfimage.png
    - images/google.png
    - images/microsoft.png
    - images/apple.png
    - images/laptop.png
    - images/wifi.png
    - images/laptopes.png
    - images/mobiles.png
    - images/modem.png
    - images/arrow.png
    - images/edit.png
    - images/profile.png
    - images/add.png
    - images/ticket.png
    - images/group.png
    - images/right.png
    - images/gfgreen.png
    - images/grouptwo.png
    - images/secondBG.png
    - images/gb_primary.png
    - images/addGreen.png
    - images/ticketGreen.png
    - images/dateGreen.png
    - images/date.png
    - images/house.png
    - images/backWhiteIcon.png